### ISSUE TITLE
puppetwash's root should reflect script name

### ISSUE THREAD

**Issue by ekinanp** [timidri/puppetwash#19]
Wash's external plugin interface expects the plugin root to match the script's basename (w/o the extension) -- it will panic otherwise. Here, the plugin root's name is `puppet` while the script is `puppetwash`. We should consolidate this.

**Comment by MikaelSmith** [comment]
What does "consolidate" mean? We have a wrapper `puppet` that's called. Is the idea to get rid of that wrapper?

**Comment by ekinanp** [comment]
Nevermind, I didn't see that. Thanks!
