### ISSUE TITLE
Add a base level Puppet stacks directory for different connections

### ISSUE THREAD

**Issue by logicminds** [timidri/puppetwash#23]
## Use Case
Many organizations run multiple puppet stacks (DEV, QA, PROD) or even many PROD Puppet stacks.  I would like the ability to have a connection profile for each stack so that I can view my stacks and `cd` into each stack to see the contents below them (nodes, reports, catalogs, ...). 

Additionally, if you manage different orgs with different puppet DBs, you can have everything setup already as unique stacks.

## Describe the Solution You Would Like
1. Allow user to setup a connection profiles file for all the stacks  ( similar to how aws profile works)
2. Allow a default profile
3. Allow a profile to be named 
4. Connect to the profile when the user runs `cd /puppet/dev_stack/`
5. `ls /puppet/` would show available stacks

All other features available in this plugin are available under the stack_name directory.

## Describe Alternatives You've Considered
N/A

## Additional Context
N/A

**Comment by logicminds** [comment]
oh snap.  This is already how it operates.

**Comment by MikaelSmith** [comment]
Is there some documentation that would make that clearer, or did you just overlook it?

**Comment by logicminds** [comment]
I suppose connection profile is better wording than a puppet instance. It wasn't clear what an instance was till I saw the wash configuration file and noticed how it was being used.
